# Generated by Config-to-Code. Review before use.

data "aws_region" "current" {}

resource "aws_ecs_cluster" "main" {
  count = var.compute_type == "ecs_fargate" ? 1 : 0
  name  = "orders-api-production-cluster"
}

resource "aws_iam_role" "task_execution" {
  count = var.compute_type == "ecs_fargate" ? 1 : 0
  name  = "orders-api-production-ecs-task-execution"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Principal = { Service = "ecs-tasks.amazonaws.com" }
      Action = "sts:AssumeRole"
    }]
  })
}

resource "aws_ecs_task_definition" "main" {
  count                    = var.compute_type == "ecs_fargate" ? 1 : 0
  family                   = "orders-api-production"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = var.cpu
  memory                   = var.memory
  execution_role_arn       = aws_iam_role.task_execution[0].arn

  container_definitions = jsonencode([{
    name      = "app"
    image     = "public.ecr.aws/nginx/nginx:stable"
    essential = true
    logConfiguration = {
      logDriver = "awslogs"
      options = {
        awslogs-group         = var.log_group_name
        awslogs-region        = data.aws_region.current.name
        awslogs-stream-prefix = "ecs"
      }
    }
  }])
}

resource "aws_ecs_service" "main" {
  count           = var.compute_type == "ecs_fargate" ? 1 : 0
  name            = "orders-api-production-service"
  cluster         = aws_ecs_cluster.main[0].id
  task_definition = aws_ecs_task_definition.main[0].arn
  desired_count   = var.desired_count
  launch_type     = "FARGATE"

  network_configuration {
    subnets          = var.subnet_ids
    security_groups  = compact([var.security_group_id])
    assign_public_ip = false
  }
}
