# Generated by Config-to-Code. Review before use.

variable "project_slug" { type = string }
variable "environment" { type = string }
variable "compute_type" { type = string }
variable "cpu" { type = number }
variable "memory" { type = number }
variable "desired_count" { type = number }
variable "subnet_ids" { type = list(string) }
variable "security_group_id" { type = string }
variable "log_group_name" { type = string }
