# Generated by Config-to-Code. Review before use.

data "aws_availability_zones" "available" {
  state = "available"
}

resource "aws_vpc" "main" {
  count                = var.mode == "private_vpc" ? 1 : 0
  cidr_block           = "10.0.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support   = true

  tags = {
    Name = "orders-api-production-vpc"
  }
}

resource "aws_subnet" "public" {
  count                   = var.mode == "private_vpc" ? var.public_subnets : 0
  vpc_id                  = aws_vpc.main[0].id
  cidr_block              = cidrsubnet(aws_vpc.main[0].cidr_block, 8, count.index)
  availability_zone       = data.aws_availability_zones.available.names[count.index]
  map_public_ip_on_launch = true

  tags = {
    Name = "orders-api-production-public-${count.index + 1}"
  }
}

resource "aws_subnet" "private" {
  count             = var.mode == "private_vpc" ? var.private_subnets : 0
  vpc_id            = aws_vpc.main[0].id
  cidr_block        = cidrsubnet(aws_vpc.main[0].cidr_block, 8, count.index + 100)
  availability_zone = data.aws_availability_zones.available.names[count.index]

  tags = {
    Name = "orders-api-production-private-${count.index + 1}"
  }
}

resource "aws_internet_gateway" "main" {
  count  = var.mode == "private_vpc" ? 1 : 0
  vpc_id = aws_vpc.main[0].id

  tags = {
    Name = "orders-api-production-igw"
  }
}

resource "aws_eip" "nat" {
  count  = var.mode == "private_vpc" && var.nat_gateway ? 1 : 0
  domain = "vpc"

  tags = {
    Name = "orders-api-production-nat-eip"
  }
}

resource "aws_nat_gateway" "main" {
  count         = var.mode == "private_vpc" && var.nat_gateway ? 1 : 0
  allocation_id = aws_eip.nat[0].id
  subnet_id     = aws_subnet.public[0].id

  tags = {
    Name = "orders-api-production-nat"
  }
}

resource "aws_security_group" "workload" {
  count       = var.mode == "private_vpc" ? 1 : 0
  name        = "orders-api-production-workload"
  description = "Generated workload security group"
  vpc_id      = aws_vpc.main[0].id

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_security_group" "database" {
  count       = var.mode == "private_vpc" ? 1 : 0
  name        = "orders-api-production-database"
  description = "Generated database security group"
  vpc_id      = aws_vpc.main[0].id
}
