# Generated by Config-to-Code. Review before use.

output "vpc_id" {
  value = length(aws_vpc.main) > 0 ? aws_vpc.main[0].id : null
}

output "private_subnet_ids" {
  value = [for subnet in aws_subnet.private : subnet.id]
}

output "public_subnet_ids" {
  value = [for subnet in aws_subnet.public : subnet.id]
}

output "workload_security_group_id" {
  value = length(aws_security_group.workload) > 0 ? aws_security_group.workload[0].id : null
}

output "database_security_group_id" {
  value = length(aws_security_group.database) > 0 ? aws_security_group.database[0].id : null
}
