# Generated by Config-to-Code. Review before use.

variable "project_slug" { type = string }
variable "environment" { type = string }
variable "region" { type = string }
variable "mode" { type = string }
variable "public_subnets" { type = number }
variable "private_subnets" { type = number }
variable "nat_gateway" { type = bool }
