# Generated by Config-to-Code. Review before use.

resource "aws_s3_bucket" "main" {
  count  = var.s3_enabled ? 1 : 0
  bucket = "orders-api-production-artifacts"
}

resource "aws_s3_bucket_public_access_block" "main" {
  count                   = var.s3_enabled && var.block_public_access ? 1 : 0
  bucket                  = aws_s3_bucket.main[0].id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_server_side_encryption_configuration" "main" {
  count  = var.s3_enabled && var.encryption_enabled ? 1 : 0
  bucket = aws_s3_bucket.main[0].id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}
