# Generated by Config-to-Code. Review before use.

variable "project_slug" { type = string }
variable "environment" { type = string }
variable "s3_enabled" { type = bool }
variable "block_public_access" { type = bool }
variable "encryption_enabled" { type = bool }
