# Generated by Config-to-Code. Review before use.

resource "aws_cloudwatch_log_group" "app" {
  count             = var.cloudwatch_enabled ? 1 : 0
  name              = "/config-to-code/orders-api-production"
  retention_in_days = 30
}
