# Generated by Config-to-Code. Review before use.

resource "aws_db_subnet_group" "main" {
  count      = var.database_type == "rds_postgres" && length(var.subnet_ids) > 0 ? 1 : 0
  name       = "orders-api-production-db-subnets"
  subnet_ids = var.subnet_ids
}

resource "aws_db_instance" "main" {
  count                  = var.database_type == "rds_postgres" ? 1 : 0
  identifier             = "orders-api-production-postgres"
  engine                 = "postgres"
  engine_version         = "16"
  instance_class         = "db.t4g.micro"
  allocated_storage      = 20
  db_name                = "app"
  username               = "app_admin"
  manage_master_user_password = true
  skip_final_snapshot    = true
  publicly_accessible    = var.publicly_accessible
  storage_encrypted      = var.encrypted
  backup_retention_period = var.backups_enabled ? 7 : 0
  multi_az               = var.multi_az
  db_subnet_group_name   = length(aws_db_subnet_group.main) > 0 ? aws_db_subnet_group.main[0].name : null
  vpc_security_group_ids = compact([var.security_group_id])
}
