# Generated by Config-to-Code. Review before use.

variable "project_slug" { type = string }
variable "environment" { type = string }
variable "database_type" { type = string }
variable "subnet_ids" { type = list(string) }
variable "security_group_id" { type = string }
variable "publicly_accessible" { type = bool }
variable "encrypted" { type = bool }
variable "backups_enabled" { type = bool }
variable "multi_az" { type = bool }
