# Generated by Config-to-Code. Review before use.

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    archive = {
      source  = "hashicorp/archive"
      version = "~> 2.4"
    }
  }
}

provider "aws" {
  region = var.region

  default_tags {
    tags = {
      Project     = var.project_slug
      Environment = var.environment
      ManagedBy   = "config-to-code"
    }
  }
}

module "network" {
  source = "../../modules/network"

  project_slug    = var.project_slug
  environment     = var.environment
  region          = var.region
  mode            = var.networking_mode
  public_subnets  = var.public_subnets
  private_subnets = var.private_subnets
  nat_gateway     = var.nat_gateway
}

module "compute" {
  source = "../../modules/compute"

  project_slug        = var.project_slug
  environment         = var.environment
  compute_type        = var.compute_type
  cpu                 = var.cpu
  memory              = var.memory
  desired_count       = var.desired_count
  subnet_ids          = module.network.private_subnet_ids
  security_group_id   = module.network.workload_security_group_id
  log_group_name      = module.monitoring.log_group_name
}

module "database" {
  source = "../../modules/database"

  project_slug        = var.project_slug
  environment         = var.environment
  database_type       = var.database_type
  subnet_ids          = module.network.private_subnet_ids
  security_group_id   = module.network.database_security_group_id
  publicly_accessible = var.database_publicly_accessible
  encrypted           = var.database_encrypted
  backups_enabled     = var.database_backups_enabled
  multi_az            = var.database_multi_az
}

module "storage" {
  source = "../../modules/storage"

  project_slug          = var.project_slug
  environment           = var.environment
  s3_enabled            = var.s3_enabled
  block_public_access   = var.s3_block_public_access
  encryption_enabled    = var.s3_encryption_enabled
}

module "monitoring" {
  source = "../../modules/monitoring"

  project_slug       = var.project_slug
  environment        = var.environment
  cloudwatch_enabled = var.cloudwatch_enabled
}
