# Generated by Config-to-Code. Review before use.

output "network_id" {
  value = module.network.vpc_id
}

output "compute_service_name" {
  value = module.compute.service_name
}

output "database_identifier" {
  value = module.database.database_identifier
}

output "storage_bucket_name" {
  value = module.storage.bucket_name
}

output "log_group_name" {
  value = module.monitoring.log_group_name
}
