# Generated by Config-to-Code. Review before use.

project_slug = "orders-api"
environment  = "production"
region       = "us-east-1"

networking_mode = "private_vpc"
public_subnets  = 2
private_subnets = 2
nat_gateway     = true

compute_type  = "ecs_fargate"
cpu           = 256
memory        = 512
desired_count = 6

database_type                = "rds_postgres"
database_publicly_accessible = false
database_encrypted           = true
database_backups_enabled     = true
database_multi_az            = true

s3_enabled             = true
s3_block_public_access = true
s3_encryption_enabled  = true

cloudwatch_enabled = true
